#!/usr/bin/env sh

host=the0x539@pub.colonq.computer

rsync -u index.html $host:public_html/bells.html
rsync -u index.js screen.css worker.js $host:public_html/
rsync -u pkg/muzak_web.js pkg/muzak_web_bg.wasm $host:public_html/pkg/
